<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--
    Promise实例.then()返回的是一个【新的Promise实例】，它的值和状态由什么决定？
        1、简单表述：由then()所指定的回调函数执行的结果决定
        2、详细表述：
            a、如果then所指定的回调返回的是非Promise值a,
                那么【新的Promise实例】状态为：成功(fulfilled)，成功的value为a
            b、如果then所指定的回调返回的是一个Promise实例p,
                那么【新的Promise实例】状态、值都与p一致
            c、如果then所指定的回调抛出异常：
                那么【新的Promise实例】状态为rejected，reason为抛出的那个异常
-->

<script>
    const p = new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve('a')
        })
    })

    /*    const x = p.then((value) => {
            console.log('success1', value);
            // return 900;
            return Promise.resolve('a')
        }, (reason) => {
            console.log('error1', reason);
        })

        x.then((value) => {
            console.log('success2', value);
        }, (reason) => {
            console.log('error2', reason);
        })*/
    p.then(
        (value) => {
            console.log('success1', value);
            return Promise.reject('a')
        }, (reason) => {
            console.log('error1', reason);
        }).then(
        (value) => {
            console.log('success2', value);
            return true
        }, (reason) => {
            console.log('error2', reason);
            throw 900
        }).then(
        (value) => {
            console.log('success3', value);
            return false
        }, (reason) => {
            console.log('error3', reason);
            return false
        }).then(
        (value) => {
            console.log('success4', value);
            return -100
        }, (reason) => {
            console.log('error4', reason);
        })

    /**
     * success1 a
     * error2 a
     * error3 900
     * success4 false
     * */

</script>
</body>
</html>